config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  scope '(:locale)', locale: /en|cat|fr/ do
    root to: 'pages#home'
    resources :menus do
      resources :meals do
        resources :allergens, only: [:create, :index, :show, :new]
        resources :meals_ingredients, only: [:create, :index, :show]
      end
      resources :drinks do
        resources :drinks_ingredients, only: [:create, :index, :show]
      end
    end
  end
end

app/models/allergen.rb
class Allergen < ApplicationRecord
  belongs_to :meals
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drink.rb
class Drink < ApplicationRecord
  belongs_to :menu
end

app/models/drinks_ingredient.rb
class DrinksIngredient < ApplicationRecord
  belongs_to :drinks
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :menu
  has_one_attached :photo
end

app/models/meals_ingredient.rb
class MealsIngredient < ApplicationRecord
  belongs_to :meals
end

app/models/menu.rb
class Menu < ApplicationRecord
    has_many :meals, dependent: :destroy
    has_many :drinks, dependent: :destroy
    has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one_attached :avatar, dependent: :destroy
end

app/controllers/allergens_controller.rb
class AllergensController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_locale

  def set_locale
    I18n.locale = params.fetch(:locale, I18n.default_locale).to_sym
  end

  def default_url_options
    { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
  end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
end

app/controllers/drinks_ingredients_controller.rb
class DrinksIngredientsController < ApplicationController
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
    skip_before_action :authenticate_user!, only: [:index, :show]

    def index
        @meals= Meal.all
    end

    def show
      @meal= Meal.find(params[:id])
    end

    def new
        @menu = Menu.find(params[:menu_id])
        @meal = Meal.new
      end
    
    def create
        @menu = Menu.find(params[:menu_id])
        @meal = Meal.new(meal_params)
        # @meal.user = current_user
        @meal.menu = @menu
        #----PROVISORY LINE----
        @meal.medio_dia_type = true
        #----PROVISORY LINE----

        if @meal.save
          redirect_to @menu, notice: "Menú cargado correctamente"
        else
            render :new
        end
    end


    private

    def meal_params
      params.require(:meal).permit(:photo)
    end
end

app/controllers/meals_ingredients_controller.rb
class MealsIngredientsController < ApplicationController
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
    skip_before_action :authenticate_user!, only: [:index, :show]

    def index
        @menus = Menu.all
        # @days = ["Monday", "Tuesday","Wednesday","Thursday","Friday"]
        # @include = @days.include? Date.today.strftime("%A")
        # @menus.each do |menu|
        #     if menu.medio_dia_type == true && @include == true
        #             menu.active = true
        #         else
        #            menu.active = false
        #     end
        # end
    end

    def show
        @menu = Menu.find(params[:id])
        @menus = Menu.all
        @meals = Meal.all
        @drinks = Drink.all
    end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NouGranados</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Roboto:wght@500&display=swap" rel="stylesheet">
    <link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'apple-icon-57x57.png' %>">
    <link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'apple-icon-60x60.png' %>">
    <link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'apple-icon-72x72.png' %>">
    <link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'apple-icon-76x76.png' %>">
    <link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'apple-icon-114x114.png' %>">
    <link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'apple-icon-120x120.png' %>">
    <link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'apple-icon-144x144.png' %>">
    <link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'apple-icon-152x152.png' %>">
    <link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'apple-icon-180x180.png' %>">
    <link rel="icon" type="image/png" sizes="192x192"  href="<%= image_path 'android-icon-192x192.png' %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'favicon-32x32.png' %>">
    <link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'favicon-96x96.png' %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'favicon-16x16.png' %>">
    <link rel="manifest" href="/manifest.json">

    <%= image_path '' %>

    <meta name="og:title" content="9 Granados">
    <meta name="og:description" content="¡Bienvenidos al restaurante 9 Granados!">
    <meta property="og:image" content="https://res.cloudinary.com/dfyhqslry/image/upload/v1596625128/facebook_dinner_kuptui.jpg">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>
    
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/meals/new.html.erb
<div class="main-container w-100" >
    <h2 class="mb-5 mt-5">Subir menú</h2>
    <%= simple_form_for([@menu, @meal]) do |f| %>
        <%= f.error_notification %>
        <%= f.input :photo, as: :file, input_html: { class: "photo-input"} %>
        <%= f.submit class: 'green-button w-50 mt-5' %>
    <% end %>
</div>

app/views/menus/index.html.erb
<div class="first-section">
    <a href="../<%= params[:locale] %>"> 
        <i class="fa fa-arrow-left mr-2 back-arrow"  aria-hidden="true"></i>
    </a>
    <div class="header">
        <h2>9 Granados</h2>
    </div>
</div>

<% @menus.each do |menu| %>
    <%@days = ["Monday", "Tuesday","Wednesday","Thursday","Friday", "Saturday", "Sunday"] %>
    <% if @days.include? Date.today.strftime("%A")%>
        <%= link_to menu_path(menu) do%>
            <div class="menu">
                <div class='menu-card' style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path menu.photo.key if menu.photo.attached? %>')">
                    <% if params[:locale] == "cat" %>
                        <h5><%= menu.name_cat %></h5> 
                    <% elsif params[:locale] == "en" %>
                        <h5><%= menu.name_en %></h5>
                    <% elsif params[:locale] == "fr" %>
                        <h5><%= menu.name_fr %></h5>
                    <% else %>
                      <h5><%= menu.name %></h5>
                    <% end %>
                    
                </div>
            </div>
        <% end %>
    <% else %>
        <% if menu.medio_dia_type != true %>
            <%= link_to menu_path(menu) do%>
                <div class="menu">
                    <div class='menu-card' style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path menu.photo.key if menu.photo.attached? %>')">
                        <h5><%= menu.name %></h5>
                    </div>
                </div>
            <% end %>
        <% end %>
    <% end %>
<% end %>

app/views/menus/show.html.erb
<div class="first-section sticky">
    <a href="../menus">
        <i class="fa fa-arrow-left mr-2 back-arrow"  aria-hidden="true"></i>
    </a>
    <div class="header">
        <h2>9 Granados</h2>
    </div>
</div>

<%# Original code for this page is in aperitive_show file%>

<h5 style="padding: 200px 30px 0 30px; tex-align: center"><%= t('home.hello') %></h5>

app/views/pages/home.html.erb
<%= render 'shared/navbar' %>
<div class="banner">
</div>
<div class="header-home">
    <h2>9 Granados</h2>
    <h5>Restaurante</h5>
</div>
<div class="main-container mt-3">
    <div class="welcome">
        <p><%= t('home.hello') %></p>
    </div>
    <div class="green-button-position">
        <div class="green-button">
            <%= link_to t('home.menus'), menus_path%>
        </div>
    </div>
</div>

app/views/shared/_carta_aperitive_show.html.erb
<div class="background-show">
    <div class="carta-back">
        <div class="tab-content" id="pills-tabContent">
            <div class="tab-pane fade show active" id="aperitive" role="tabpanel" aria-labelledby="aperitive-tab">
                <h2 style="text-align: center; padding-top: 10px; color: white;"><%= t('menues.show_drink.aperitivo') %></h2>
                <h5 style="color: white;" class="mt-3 pl-3 pr-3"><%= t('menues.show_9granados.terraza') %></h5>
                <div class="separate">
                </div>
                <div class="">
                    <% @drinks.each do |drink|  %>
                        <% if drink.aperitive == true %>
                        <div class="name-price-carta meal-card">
                            <% if params[:locale] == "cat" %>
                                    <h5><%= drink.name_cat %></h5>
                                    <p class="mt-3"><%= drink.description_cat %></p>
                                <% elsif params[:locale] == "en" %>
                                    <h5><%= drink.name_en %></h5>
                                    <p class="mt-3"><%= drink.description_en %></p>
                                <% elsif params[:locale] == "fr" %>
                                    <h5><%= drink.name_fr %></h5>
                                    <p class="mt-3"><%= drink.description_fr %></p>    
                                <% else %>
                                    <h5><%= drink.name %></h5>
                                    <p class="mt-3"><%= drink.description %></p> 
                                <% end %>
                            <h6 class="price"><%= drink.price %>€</h6>
                        </div>
                        <div class="separate">
                        </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
            <div class="tab-pane fade" id="beer" role="tabpanel" aria-labelledby="beer-tab">
                <h2 style="text-align: center; padding-top: 10px; color: white;"><%= t('menues.show_drink.cerveza') %></h2>
                <div class="separate">
                </div>
                <div class="">
                    <% @drinks.each do |drink|  %>
                        <% if drink.beer == true %>
                        <div class="name-price-carta meal-card">
                            <% if params[:locale] == "cat" %>
                                    <h5><%= drink.name_cat %></h5>
                                    <p class="mt-3"><%= drink.description_cat %></p>
                                <% elsif params[:locale] == "en" %>
                                    <h5><%= drink.name_en %></h5>
                                    <p class="mt-3"><%= drink.description_en %></p>
                                <% elsif params[:locale] == "fr" %>
                                    <h5><%= drink.name_fr %></h5>
                                    <p class="mt-3"><%= drink.description_fr %></p>    
                                <% else %>
                                    <h5><%= drink.name %></h5>
                                    <p class="mt-3"><%= drink.description %></p> 
                                <% end %>
                            <h6 class="price"><%= drink.price %>€</h6>
                        </div>
                        <div class="separate">
                        </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
            <div class="tab-pane fade" id="rum" role="tabpanel" aria-labelledby="rum-tab">
                <h2 style="text-align: center; padding-top: 10px; color: white;"><%= t('menues.show_drink.ron') %></h2>
                <div class="separate">
                </div>
                <div class="">
                    <% @drinks.each do |drink|  %>
                        <% if drink.rum == true || drink.gin == true || drink.vodka == true %>
                        <div class="name-price-carta meal-card">
                            <% if params[:locale] == "cat" %>
                                    <h5><%= drink.name_cat %></h5>
                                    <p class="mt-3"><%= drink.description_cat %></p>
                                <% elsif params[:locale] == "en" %>
                                    <h5><%= drink.name_en %></h5>
                                    <p class="mt-3"><%= drink.description_en %></p>
                                <% elsif params[:locale] == "fr" %>
                                    <h5><%= drink.name_fr %></h5>
                                    <p class="mt-3"><%= drink.description_fr %></p>    
                                <% else %>
                                    <h5><%= drink.name %></h5>
                                    <p class="mt-3"><%= drink.description %></p> 
                                <% end %>
                            <h6 class="price"><%= drink.price %>€</h6>
                        </div>
                        <div class="separate">
                        </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
            <div class="tab-pane fade" id="whiskey" role="tabpanel" aria-labelledby="whiskey-tab">
                <h2 style="text-align: center; padding-top: 10px; color: white;"><%= t('menues.show_drink.whiskey') %></h2>
                <div class="separate">
                </div>
                <div class="">
                    <% @drinks.each do |drink|  %>
                        <% if drink.whiskey == true %>
                        <div class="name-price-carta meal-card">
                            <% if params[:locale] == "cat" %>
                                    <h5><%= drink.name_cat %></h5>
                                    <p class="mt-3"><%= drink.description_cat %></p>
                                <% elsif params[:locale] == "en" %>
                                    <h5><%= drink.name_en %></h5>
                                    <p class="mt-3"><%= drink.description_en %></p>
                                <% elsif params[:locale] == "fr" %>
                                    <h5><%= drink.name_fr %></h5>
                                    <p class="mt-3"><%= drink.description_fr %></p>    
                                <% else %>
                                    <h5><%= drink.name %></h5>
                                    <p class="mt-3"><%= drink.description %></p> 
                                <% end %>
                            <h6 class="price"><%= drink.price %>€</h6>
                        </div>
                        <div class="separate">
                        </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>
<%# TAB %>
            <div class="navbar navbar-expand-sm navbar-light navbar-meals w-100">
                <ul class="nav nav-pills tab-menu" id="pills-tab" role="tablist">
                    <li class="nav-item col-6">
                        <a class="nav-link active" id="own-events-tab" data-toggle="pill" href="#aperitive" role="tab" aria-controls="aperitive" aria-selected="true"><%= t('menues.show_drink.aperitivo') %></a>
                    </li>
                    <li class="nav-item col-6">
                        <a class="nav-link" id="applied-events-tab" data-toggle="pill" href="#beer" role="tab" aria-controls="beer" aria-selected="false"><%= t('menues.show_drink.cerveza') %></a>
                    </li>
                    <li class="nav-item col-6">
                        <a class="nav-link" id="favorites-tab" data-toggle="pill" href="#rum" role="tab" aria-controls="rum" aria-selected="false"><%= t('menues.show_drink.ron') %></a>
                    </li>
                    <li class="nav-item col-6">
                        <a class="nav-link" id="favorites-tab" data-toggle="pill" href="#whiskey" role="tab" aria-controls="whiskey" aria-selected="false"><%= t('menues.show_drink.whiskey') %></a>
                    </li>
                </ul>
            </div>

<% if @menu.menu_type == true %>
    <%= render "shared/menushow" %>
<% elsif @menu.drink_type == true  %>
    <%= render "shared/carta_drinks_show" %>
<% elsif @menu.aperitive_type == true  %>
    <%= render "shared/carta_aperitive_show" %>
<% elsif @menu.medio_dia_type == true  %>
    <%= render "shared/medio_dia_show" %>
<% else %>
    <%= render "shared/cartashow" %>
<% end %>

app/views/shared/_carta_drinks_show.html.erb
<div class="background-show">
    <div class="carta-back">
        <div class="tab-content" id="pills-tabContent">
            <div class="tab-pane fade show active" id="tinto" role="tabpanel" aria-labelledby="tinto-tab">
                <h2 style="text-align: center; padding-top: 10px; color: white;"><%= t('menues.show_drink.tinto') %></h2>
                <div class="separate">
                </div>
                <div class="">
                    <% @drinks.each do |drink|  %>
                        <% if drink.red == true %>
                        <div class="name-price-carta meal-card">
                            <% if params[:locale] == "cat" %>
                                    <h5><%= drink.name_cat %></h5>
                                    <p class="mt-3"><%= drink.description_cat %></p>
                                <% elsif params[:locale] == "en" %>
                                    <h5><%= drink.name_en %></h5>
                                    <p class="mt-3"><%= drink.description_en %></p>
                                <% elsif params[:locale] == "fr" %>
                                    <h5><%= drink.name_fr %></h5>
                                    <p class="mt-3"><%= drink.description_fr %></p>    
                                <% else %>
                                    <h5><%= drink.name %></h5>
                                    <p class="mt-3"><%= drink.description %></p> 
                                <% end %>
                                <% if drink.price_glass.nil? %>
                                <h6 class="price"><%= drink.price %>€</h6>
                            <% else %>
                                <div class="prices-box">
                                    <h6 class="price"><%= drink.price_glass %>€ / </h6>
                                    <h6 class="price"><%= drink.price %>€</h6>
                                </div>
                            <% end %>
                        </div>
                        <div class="separate">
                        </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
            <div class="tab-pane fade" id="blanco" role="tabpanel" aria-labelledby="blanco-tab">
                <h2 style="text-align: center; padding-top: 10px; color: white;"><%= t('menues.show_drink.blanco') %></h2>
                <div class="separate">
                </div>
                <div class="">
                    <% @drinks.each do |drink|  %>
                        <% if drink.white == true %>
                        <div class="name-price-carta meal-card">
                            <% if params[:locale] == "cat" %>
                                    <h5><%= drink.name_cat %></h5>
                                    <p class="mt-3"><%= drink.description_cat %></p>
                                <% elsif params[:locale] == "en" %>
                                    <h5><%= drink.name_en %></h5>
                                    <p class="mt-3"><%= drink.description_en %></p>
                                <% elsif params[:locale] == "fr" %>
                                    <h5><%= drink.name_fr %></h5>
                                    <p class="mt-3"><%= drink.description_fr %></p>    
                                <% else %>
                                    <h5><%= drink.name %></h5>
                                    <p class="mt-3"><%= drink.description %></p> 
                                <% end %>
                                <% if drink.price_glass.nil? %>
                                <h6 class="price"><%= drink.price %>€</h6>
                            <% else %>
                                <div class="prices-box">
                                    <h6 class="price"><%= drink.price_glass %>€ / </h6>
                                    <h6 class="price"><%= drink.price %>€</h6>
                                </div>
                            <% end %>
                        </div>
                        <div class="separate">
                        </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
            <div class="tab-pane fade" id="rosado" role="tabpanel" aria-labelledby="rosado-tab">
                <h2 style="text-align: center; padding-top: 10px; color: white;"><%= t('menues.show_drink.rosado') %></h2>
                <div class="separate">
                </div>
                <div class="">
                    <% @drinks.each do |drink|  %>
                        <% if drink.rose == true %>
                        <div class="name-price-carta meal-card">
                            <% if params[:locale] == "cat" %>
                                    <h5><%= drink.name_cat %></h5>
                                    <p class="mt-3"><%= drink.description_cat %></p>
                                <% elsif params[:locale] == "en" %>
                                    <h5><%= drink.name_en %></h5>
                                    <p class="mt-3"><%= drink.description_en %></p>
                                <% elsif params[:locale] == "fr" %>
                                    <h5><%= drink.name_fr %></h5>
                                    <p class="mt-3"><%= drink.description_fr %></p>    
                                <% else %>
                                    <h5><%= drink.name %></h5>
                                    <p class="mt-3"><%= drink.description %></p> 
                                <% end %>
                                <% if drink.price_glass.nil? %>
                                <h6 class="price"><%= drink.price %>€</h6>
                            <% else %>
                                <div class="prices-box">
                                    <h6 class="price"><%= drink.price_glass %>€ / </h6>
                                    <h6 class="price"><%= drink.price %>€</h6>
                                </div>
                            <% end %>
                        </div>
                        <div class="separate">
                        </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
            <div class="tab-pane fade" id="cava" role="tabpanel" aria-labelledby="cava-tab">
                <h2 style="text-align: center; padding-top: 10px; color: white;">Cava</h2>
                <div class="separate">
                </div>
                <div class="">
                    <% @drinks.each do |drink|  %>
                        <% if drink.cava == true %>
                        <div class="name-price-carta meal-card">
                            <% if params[:locale] == "cat" %>
                                    <h5><%= drink.name_cat %></h5>
                                    <p class="mt-3"><%= drink.description_cat %></p>
                                <% elsif params[:locale] == "en" %>
                                    <h5><%= drink.name_en %></h5>
                                    <p class="mt-3"><%= drink.description_en %></p>
                                <% elsif params[:locale] == "fr" %>
                                    <h5><%= drink.name_fr %></h5>
                                    <p class="mt-3"><%= drink.description_fr %></p>    
                                <% else %>
                                    <h5><%= drink.name %></h5>
                                    <p class="mt-3"><%= drink.description %></p> 
                                <% end %>
                                <% if drink.price_glass.nil? %>
                                <h6 class="price"><%= drink.price %>€</h6>
                            <% else %>
                                <div class="prices-box">
                                    <h6 class="price"><%= drink.price_glass %>€ / </h6>
                                    <h6 class="price"><%= drink.price %>€</h6>
                                </div>
                            <% end %>
                        </div>
                        <div class="separate">
                        </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>
<%# TAB %>
            <div class="navbar navbar-expand-sm navbar-light navbar-meals w-100">
                <ul class="nav nav-pills tab-menu" id="pills-tab" role="tablist">
                    <li class="drink-item col-6">
                        <a class="nav-link active" id="own-events-tab" data-toggle="pill" href="#tinto" role="tab" aria-controls="tinto" aria-selected="true"><%= t('menues.show_drink.tinto') %></a>
                    </li>
                    <li class="drink-item col-6">
                        <a class="nav-link" id="applied-events-tab" data-toggle="pill" href="#blanco" role="tab" aria-controls="blanco" aria-selected="false"><%= t('menues.show_drink.blanco') %></a>
                    </li>
                    <li class="drink-item col-6">
                        <a class="nav-link" id="favorites-tab" data-toggle="pill" href="#rosado" role="tab" aria-controls="rosado" aria-selected="false"><%= t('menues.show_drink.rosado') %></a>
                    </li>
                    <li class="drink-item col-6">
                        <a class="nav-link" id="favorites-tab" data-toggle="pill" href="#cava" role="tab" aria-controls="cava" aria-selected="false">Cava</a>
                    </li>
                </ul>
            </div>

app/views/shared/_flag.html.erb
    <div class="flag-container">
        <div class="flag-box">
        <a href="/cat">
            <img class="flag" src="https://res.cloudinary.com/dfyhqslry/image/upload/v1594146282/Nou%20granados/Flags/catalonia_rvcrss.png" alt="">
        </a>
        <a href="/">
            <img class="flag" src="https://res.cloudinary.com/dfyhqslry/image/upload/v1594146742/Nou%20granados/Flags/Spain_yx31ax.png" alt="">
        </a>
        <a href="/en">
            <img class="flag" src="https://res.cloudinary.com/dfyhqslry/image/upload/v1594146742/Nou%20granados/Flags/England_cnldoa.png" alt="">
        </a>
        <a href="/fr">
            <img class="flag" src="https://res.cloudinary.com/dfyhqslry/image/upload/v1594146742/Nou%20granados/Flags/France_nf8v8a.png" alt="">
        </a>
        </div>
    </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_medio_dia_show.html.erb
<br><br><br>
<% @menus.each do |menu| %>
    <% if menu.medio_dia_type %>
        <% meal = menu.meals.last %>
        <div class='medio-dia' style="background-image: url('<%= cl_image_path meal.photo.key if meal.photo.attached? %>')">
        </div>
    <% end %>
<% end %>

<script>
    $("document").ready( function () {
        alert("<%= t('home.hello') %>");
    }); 
</script>

app/views/shared/_navbar.html.erb
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <a class="navbar-brand" href="/users/sign_in">
        <%= image_tag "https://res.cloudinary.com/dfyhqslry/image/upload/v1593498769/Nou%20granados/cropped-9G_petit_e2uemr.jpg" %>
      </a>
    <% if current_user %>
      <div data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <%= image_tag "https://res.cloudinary.com/dfyhqslry/image/upload/v1593708081/Nou%20granados/victor_ciiwzw.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <i class="fas fa-sort-down"></i>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%@menus = Menu.all  %>
          <% id_medio_dia = ""  %>
            <% @menus.each do |menu|  %>
            <% if menu.medio_dia_type == true %>
              <% id_medio_dia = menu.id %>
            <% end %>
          <% end %>
          <a class="dropdown-item" href="menus/<%= id_medio_dia %>/meals/new">Subir menú</a>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"dropdown-item"%>
        </div>
      </div>
    <% else %>
    <div id="navbarSupportedContent">
    <%= render "shared/flag" %>
    <% end %>
    </div>
  </div>